### ISSUE TITLE
Wierd status behaviour 

### ISSUE THREAD

**Issue by cofeek-codes** [ncalteen/branch-enforcement#154]
### Details

My test is running fine but the status check remains "Waiting to be reported" regardless of whether the test passed or not. What am i doing wrong?
**Action code**
```yaml
name: Branch Enforcement

on:
  pull_request:

jobs:
  check-branch:
    name: Check Branches
    runs-on: ubuntu-latest

    permissions:
      statuses: write

    env:
      # The branch being merged.
      HEAD_REF: ${{ github.head_ref }}
      # The target branch.
      BASE_REF: ${{ github.base_ref }}

    steps:
      # Policy:
      #   - Any branch can be merged into dev (e.g. feature branches)
      #   - dev can be merged into qa
      #   - qa can be merged into main
      - name: Enforce Merge Policy
        id: enforce-policy
        uses: ncalteen/branch-enforcement@v2
        with:
          policy: |
            *:dev
            dev:test
            test:prod
          head_ref: ${{ env.HEAD_REF }}
          base_ref: ${{ env.BASE_REF }}

      # This step should not run if the branch policy is not met.
      - name: Policy Passed
        id: passed
        run: echo "This PR passes the merge policy!"
```
**Branch protection rule**
![image](https://github.com/user-attachments/assets/c002d747-2347-4aa6-b494-5ab3d5b75e50)

**Failed run**
![image](https://github.com/user-attachments/assets/a198067a-53ba-46e4-99df-1b74b5ffa37a)

**Successful run**
![image](https://github.com/user-attachments/assets/19e7ffc1-3a8e-4e51-8e6b-2bedda22ea66)
